version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d/eclide.conf.template:/etc/nginx/conf.d/eclide.conf.template
      - ./nginx/run_nginx.sh:/etc/nginx/run_nginx.sh
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    environment:
      - NGINX_HTTP_PORT=${NGINX_HTTP_PORT}
      - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT}
      - HOSTNAME=${HOST_NAME}
      - NODE_PORT=${NODE_PORT}
    depends_on:
      - node_web
    networks:
      - ecl-ide-network
    entrypoint: [/etc/nginx/run_nginx.sh, "${HOST_NAME}"]
  node_web:
    #restart: always
    entrypoint: [/home/eclide/app/docker-entry.sh, "mysql_db", "${DB_PORT}"]
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ecl-ide-network
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:5.7
    restart: always
    command: --innodb_use_native_aio=0
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - ecl-ide-network

networks:
  ecl-ide-network:
    driver: bridge
