version: "3"
services:
  node_web:
    #restart: always
    entrypoint: [/home/eclide/app/docker-entry.sh, "mysql_db", "${DB_PORT}"]
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ecl-ide-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7
    restart: always
    command: --innodb_use_native_aio=0
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - ecl-ide-network

networks:
  ecl-ide-network:
    driver: bridge
